CHANGELOG.md
src/cli/ignores.js
tests/cli/ignores.test.js

closes https://github.com/dotenvx/dotenvx/issues/25

Remove flask env

---

CHANGELOG.md
src/cli/actions/run.js
src/cli/dotenvx.js
src/cli/helpers.js
src/shared/logger.js

closes https://github.com/dotenvx/dotenvx/issues/26

better 'missing .env' error with help next steps

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/cli/actions/encrypt.js
src/cli/actions/precommit.js
src/cli/actions/run.js
src/cli/dotenvx.js
src/cli/examples.js
src/shared/createSpinner.js

closes https://github.com/dotenvx/dotenvx/issues/29

add precommit action

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/cli/actions/run.js
src/lib/main.js

* powered by https://github.com/motdotla/dotenv-expand

default expansion 🌱

---

package-lock.json
package.json
src/cli/actions/hub/login.js
src/cli/actions/hub/push.js
src/shared/axios.js

undici is more than 3x faster, uses only one dependency compared to axios' 8 dependencies, and looks more reliable as it's maintained by some people behind node
closes #57
note that i haven't been able to test this pr, please test before merging

switch to undici for http requests

---

CHANGELOG.md
src/cli/actions/run.js
src/cli/dotenvx.js

https://github.com/dotenvx/dotenvx/issues/72

add optional flag for path to `--env-vault-file`

---

src/cli/actions/run.js
src/cli/dotenvx.js
src/lib/services/runDefault.js
tests/lib/services/runDefault.test.js

```
dotenvx run --env="HELLO=World" -- node index.js
```

`--env` flag

---

CHANGELOG.md
src/lib/helpers/dotenvVault.js
src/lib/helpers/removePersonal.js
tests/lib/helpers/dotenvVault.test.js

you can use personal environment variables
```
HELLO="World"
OTHER="dev"
HELLO="personal"
```
anything after `# personal.dotenvx.com` will not be encrypted to .env.vault

`# personal.dotenvx.com` - personal environment variables

---

src/lib/helpers/latestVersion.js
src/lib/helpers/updateNotifier.js

return current version if latest version request fails

---

.github/workflows/ci.yml
package.json

see https://github.blog/2023-04-19-introducing-npm-package-provenance/ and https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow

enable npm provenance

---

src/cli/actions/hub/pull.js
src/cli/actions/hub/push.js
src/cli/dotenvx.js

found while trying to debug windows issue
also modified update notice link as it wasn't a masked link, just plaintext

fix some links

---

README.md

chore(readme): :pencil2: fix typo

---

.github/workflows/ci.yml
CHANGELOG.md
package-lock.json
package.json
patches/pkg+5.8.1.patch
src/cli/actions/run.js

`dotenvx run -- dotenvx run -- dotenvx run -- env` now possible

handle nested dotenvx invocations

---

src/lib/main.d.ts
src/lib/services/decrypt.js
src/lib/services/encrypt.js

chore: update type definitions

---

src/lib/helpers/packageJson.js

Remove dynamic dependency on package.json

---

CHANGELOG.md
src/cli/actions/run.js
src/lib/helpers/decryptValue.js
src/lib/helpers/parseDecryptEvalExpand.js
src/lib/helpers/truncate.js
src/lib/services/decrypt.js
src/lib/services/run.js
tests/cli/actions/run.test.js
tests/lib/helpers/decryptValue.test.js
tests/lib/helpers/parseDecryptEvalExpand.test.js
tests/lib/helpers/truncate.test.js
tests/lib/services/run.test.js

surface decryption warnings to user

---

src/lib/helpers/colorDepth.js
src/shared/colors.js
tests/lib/helpers/colorDepth.test.js
tests/shared/colors.test.js

fix color detection

---

CHANGELOG.md
src/lib/main.js

expose getColor and bold

---

src/lib/services/precommit.js

fix: run precommit hook only on staged files

---

CHANGELOG.md
src/cli/actions/decrypt.js
src/cli/actions/encrypt.js
src/cli/actions/get.js
src/cli/actions/keypair.js
tests/cli/actions/decrypt.test.js
tests/cli/actions/encrypt.test.js
tests/cli/actions/get.test.js
tests/cli/actions/keypair.test.js
tests/e2e/decrypt.test.js

https://github.com/dotenvx/dotenvx/issues/386

moving to console.log

---

package-lock.json
package.json

Update eciesjs package to stable version

---

.github/workflows/ci.yml
.gitignore
esbuild.js
package-lock.json
package.json

chore(pkg): add pre-build step using esbuild

---

README.md

docs: Fix the typo in README

---

CHANGELOG.md
src/lib/helpers/parse.js
tests/lib/helpers/parse.test.js

https://github.com/dotenvx/dotenvx/issues/488

support complex command substitution combining variable expansion

---

src/lib/main.d.ts

close: https://github.com/dotenvx/dotenvx/issues/489

fix: add missing types for config options

---

.github/workflows/ci.yml

feat: Use wingetcreate for releasing to WinGet

---

src/lib/helpers/dotenvParse.js
src/lib/helpers/isFullyEncrypted.js

chore: fix typo in comment
