CHANGELOG.md
package-lock.json
package.json

received error:
```
➜  multiple dotenvx run -- node index.js
pkg/prelude/bootstrap.js:1872
throw error;
^
ReferenceError: ReadableStream is not defined
at Object.<anonymous> (/snapshot/dotenvx/node_modules/undici/lib/fetch/response.js:507:3)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Module._compile (pkg/prelude/bootstrap.js:1933:32)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at Module.require (pkg/prelude/bootstrap.js:1851:31)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> …
```

fix undici issue with build and package to binary

---

src/cli/actions/run.js
src/cli/helpers.js

Got the error as commented on #92 and @ali-layken in #99. This should fix the error for powershell users.
Haven't thoroughly tested this, but it works on my Win11 VM.
Also noticed that strings in the dotenvx run command don't get parsed right so they arrive with string keys.
Example:
`dotenvx run --env-file=.env.development --env='EXPO_PUBLIC_APP_ENV=development' --env='EXPO_NO_DOTENV=1' --`
Here I have to remove the '' around the value else they won't properly get parsed and set before running the command.
Thats probably a separate windows issue but yeah.

Fix command path detection on windows

---

package-lock.json
package.json

My organization uses a deep dependency scanning tool. This tool reports dotenvx due to an old package which is a dependency of the version of clipboardy that is used by dotenvx. Unfortunately this means I'm unable to continue using dotenvx in my organization until this is resolved.
This PR bumps clipboardy to a version which resolves the issue with dependency scanning tools. Though the version bump is a breaking change none of my testing indicated that the change would affect dotenvx.
I know PR's to bump versions are annoying but I greatly enjoy dotenvx and would like to continue using it :+1:

Bump clipboardy version

---

src/cli/actions/hub/login.js
src/cli/actions/hub/open.js

I've tried this both on the brew packages, and via yarn. When I run `dotenvx hub open` or `dotenv hub login` it throws an error:
```
/snapshot/dotenvx/src/cli/actions/hub/open.js:19
const answer = await confirm({ message: `press Enter to open [${openUrl}]...` })
^
TypeError: confirm is not a function
at Command.open (/snapshot/dotenvx/src/cli/actions/hub/open.js:19:24)
at Command.listener [as _actionHandler] (/snapshot/dotenvx/node_modules/commander/lib/command.js:494:17)
at /snapshot/dotenvx/node_modules/commander/lib/command.js:1296:65
at Command._chainOrCall (/snapshot/dotenvx/node_modules/commander/lib/command.js:1193:12)
at Command._parseCommand (/snapshot/dotenvx/node_modules/commander/lib/command.js:1296:27)
at /snapshot/dotenvx/node_modules/commander/lib/command.js:1082:27
at …
```

Fix import paths for @inquirer/confirm

---

package-lock.json
package.json
src/lib/helpers/clipboardy/windows.js

on windows systems, it's reliable to just check process.arch
the arch package has specific checks for other systems

remove `arch` dependency

---

src/cli/actions/decrypt.js
src/lib/helpers/dotenvKeys.js
src/lib/helpers/guessEnvironment.js
tests/lib/helpers/dotenvKeys.test.js
tests/lib/helpers/guessEnvironment.test.js

This adds support for files like `.env.development.local`. [NextJS](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#default-environment-variables) uses this convention to let you add defaults for development or production envs.
I needed it for use with [Plasmo](https://docs.plasmo.com/framework/env#local-env), which has adopted the pattern from NextJS.
If a `.env.[env].local` file is detected, the environment name is set to `[env]_local` when used for vault and keys. When decrypting the vault, if the name of the env contains a `_`, it is replaced by a `.` when the file is written to disk.
I've added tests for `guessEnvironment`.

add support for .env.[env].local

---

src/lib/helpers/replace.js

Not sure why the added test added in `0.43.1` passed when the bug seems to still be there. There is a single part in the regex which was causing the problem, commenting it out fixed the bug. I'm not sure what functionality this might remove.

This fixes the bug which 0.43.1 was meant to resolve. 

---

src/cli/actions/convert.js
src/cli/actions/genexample.js
src/cli/actions/get.js
src/cli/actions/gitignore.js
src/cli/actions/hub/login.js
src/cli/actions/hub/logout.js
src/cli/actions/hub/open.js
src/cli/actions/hub/pull.js
src/cli/actions/hub/push.js
src/cli/actions/hub/status.js
src/cli/actions/hub/token.js
src/cli/actions/ls.js
src/cli/actions/prebuild.js
src/cli/actions/precommit.js
src/cli/actions/run.js
src/cli/actions/scan.js
src/cli/actions/set.js
src/cli/actions/settings.js
src/cli/actions/vault/convert.js
src/cli/actions/vault/decrypt.js
src/cli/actions/vault/encrypt.js
src/cli/actions/vault/status.js
src/cli/commands/hub.js
src/cli/dotenvx.js
src/lib/main.js
src/shared/logger.js
tests/lib/config-vault.test.js
tests/lib/config.test.js
tests/shared/logger.test.js

This pull request refactors the `logger` util to export a new `setLogLevel` method which has the same logic as the log level setting in the CLI portion. The same override logic is present and can be maintained across either the CLI or the programmatic version of the library's initial config.
* Extracted log level setting logic from `dotenvx.js` into a new `setLogLevel` method in `logger.js`
* Slight readability refactor from multiple `if` statements to a ternary expression with the `Setting log level to...` log triggering for all settings except `quiet`
* Added unit tests to cover all new combinations
```javascript
dotenvx.config({
quiet: true,
verbose: true,
debug: true,
logLevel: "warn"
});
```
The CLI and programmatic configs should respect the same log level flags and override logic, …

Refactor `logger` util to share logger `level` configuration across CLI + JavaScript tools

---

src/cli/actions/encrypt.js
src/cli/dotenvx.js
src/lib/main.d.ts
src/lib/main.js
src/lib/services/encrypt.js
tests/lib/services/encrypt.test.js
tests/lib/services/ls.test.js
tests/monorepo/apps/multiple/.env

`dotenvx encrypt --key HELLO -k HELLO2`
will only encrypt those two keys for a given `.env` file like this:
```
HELLO="World"
HELLO2="Country"
HELLO3="town"
```

add `--key` option to `encrypt`

---

package-lock.json
package.json

fixes #282 by calling `patch-package` on `prepare` instead, which only runs when locally installing (never on the end user's machine) and on npm publish

make `patch-package` only run locally

---

package-lock.json
package.json
src/cli/actions/ext/genexample.js
src/cli/actions/ext/hub/login.js
src/cli/actions/ext/hub/logout.js
src/cli/actions/ext/hub/open.js
src/cli/actions/ext/hub/pull.js
src/cli/actions/ext/hub/push.js
src/cli/actions/ext/vault/decrypt.js
src/cli/actions/ext/vault/encrypt.js
src/shared/confirm.js
src/shared/createSpinner.js
tests/shared/createSpinner.test.js

- Replaces `@inquirer/confirm` ([27](https://npmgraph.js.org/?q=@inquirer/confirm@2) subdependencies) with `@clack/core` ([2](https://npmgraph.js.org/?q=%40clack%2Fcore))
- Replaces `ora` ([29](https://npmgraph.js.org/?q=ora@5.4.1) subdependencies) with a native alternative (0) based on logic provided by @PondWader
As such, this PR makes the total number of dependencies used by dotenvx go from [131](https://npmgraph.js.org/?q=@dotenvx/dotenvx@1.3.0) to just [99](https://npmgraph.js.org/?q=https%3A%2F%2Fraw.githubusercontent.com%2FSuperchupuDev%2Fdotenvx%2F08e88905aa3c21487fba953348e91672ff9243c5%2Fpackage.json) :O
Before:
After:

replace `@inquirer/confirm` and `ora`

---

CHANGELOG.md
src/cli/actions/decrypt.js
src/cli/actions/encrypt.js
src/cli/dotenvx.js
src/lib/helpers/findOrCreatePublicKey.js
src/lib/helpers/keyPair.js
src/lib/services/encrypt.js
src/lib/services/sets.js
tests/lib/helpers/findOrCreatePublicKey.test.js
tests/lib/helpers/keyPair.test.js

wip. needs to better consider usage when first running encrypt on `.env`.
it will currently modify still - because it needs to generate the DOTENV_PUBLIC_KEY. that seems unexpected when using, though it does make sense for it to be there. otherwise, we're left asking the user to pass a public key, which seems burdensome. 
have to think on this one some more.

`--stdout`

---

src/cli/dotenvx.js

👋🏼 ,
Extra extra small fix here! Basically `dotenvx decrypt --help`  says:
`keys(s) to encrypt (default: all keys in file)` instead of `keys(s) to decrypt (default: all keys in file)`
Thanks. `dotenvx` is so usefull !

Typo in  `dotenvx decrypt --help`

---

src/lib/helpers/parseDecryptEvalExpand.js

This enables delegated expansion using dynamically loaded environment files in cloud deployments, instead of shipping custom container images for each env file, or needing to deal with volume mount annoyances. You can dynamically provide an environment decryption key using `DOTENV_PRIVATE_KEY` as a cloud secret.
The solution I came up with:
`.env` (shipped in container image):
```
FOO=${FOO_ENC}
BAR=${BAR_ENC}
```
`.env.{environment}` (loaded into cloud environment using `docker --env-file`):
```
FOO_ENC=encrypted:woefijweoif
BAR_ENC=encrypted:jsdfkjfowe 
```
A bug remains where the `FOO_ENC` variables cannot be quoted - I suspect this should be fixed somewhere in the eval/expand logic but I didn't have time to dig.
An _additional_ bug remains where you cannot just do `FOO=${FOO}` in the …

Decrypt expanded values if necessary

---

package-lock.json
package.json
src/lib/services/status.js
src/shared/logger.js
tests/shared/logger.test.js

part of trying to refactor the logger to eventually remove winston, realized `chalk` can be replaced without outright removing `winston`
was originally gonna use `color-convert` but the use here can be cleanly replaced with just `color-name`, which both `chalk` and `color-convert` use
- [`chalk@4`](https://npmgraph.js.org/?q=chalk@4) - 5 subdependencies
- [`picocolors`](https://npmgraph.js.org/?q=picocolors) - 0 subdependencies
- [`color-name`](https://npmgraph.js.org/?q=color-name) - 0 subdependencies

replace `chalk` with `picocolors` and `color-name`

---

package-lock.json
package.json
src/lib/helpers/colorDepth.js
src/lib/services/status.js
src/shared/colors.js
src/shared/logger.js
tests/lib/helpers/colorDepth.test.js
tests/shared/colors.test.js
tests/shared/logger.test.js

removes `color-name`, ~~didn't remove `picocolors` due to it using standard 16 color ansi codes instead of 256~~
(above is `picocolors` red, below is ansi256 red, small difference. ~~i can remove `picocolors` if that's not a problem though~~)
removed `picocolors` as well 💪

use ansi256 colors instead of rgb

---

src/lib/services/precommit.js
tests/lib/services/precommit.test.js

This PR includes a fix to #333 which includes more context on the overall issue.
I used the [`Ls` class in `src/lib/services/ls.js`](https://github.com/dotenvx/dotenvx/blob/main/src/lib/services/ls.js) to find all the `.env*` files in the repository as part of the precommit hook. If any of these files are not encrypted the pre-commit hook will throw. 
The fix was actually pretty easy to implement, I just had to fight with the tests for awhile 😅
Let me know if there's anything else I should clean up before we can merge.

Fix: dotenvx precommit hook should check subfolders

---

CHANGELOG.md
README.md
src/cli/actions/get.js
src/cli/dotenvx.js
tests/cli/actions/get.test.js

ran into an edge case with systemd and puma that i cannot yet solve - related to `dotenvx run -- bundle exec puma` (but only with systemd). strange.
this feature gives a workaround by foregoing the wrapping run for `env`:
```
$ env $(dotenvx get --format shell) bundle exec puma
```
that will work with systemd

add `--format` option to get

---

src/lib/services/run.js

Use `options.stdio` instead of `2>os.devNull`
to suppress stderr output for dotenvx-pro cmd.
https://nodejs.org/api/os.html#osdevnull

Use `options.stdio` instead of `2>os.devNull`

---

src/lib/main.d.ts

Since TS version 5.3 (https://github.com/microsoft/TypeScript/issues/56525) it is not allowed default values in interface definition. It causes error you can see on the fig. So I suggest this patch.

TS interface fix

---

src/lib/helpers/conventions.js
tests/lib/helpers/conventions.test.js

Prior to this commit, when using `--convention=nextjs` and a non-canonical `NODE_ENV`, `dotenvx` would ignore an existing `.env.local` file.
This commit causes `dotenvx` to ignore `.env.local` only when `NODE_ENV` is `test`.
---
This is an edge case and probably not a big deal, but it seemed unintended to me considering [the way it is implemented in Next.js](https://github.com/vercel/next.js/blob/ca5f29d81b011c3a01e2372118b29836f1df0fa7/packages/next-env/index.ts#L134-L142).  An alternative would be to keep the logic the same, but log a warning when `NODE_ENV` is non-canonical.
By the way, if the previous code style (`if` + `push`) is preferred, just let me know.  I can switch back to it.

Ignore `.env.local` only when `NODE_ENV` is `test`

---

src/lib/helpers/installPrecommitHook.js

The `&>` output redirection is [not POSIX compliant][SC3020], and causes a "command not found" on some systems (e.g. Ubuntu 20.04) even when `dotenvx` is installed:
```console
$ git commit -m 'my message'
[dotenvx][precommit] 'dotenvx' command not found
[dotenvx][precommit] ? install it with [brew install dotenvx/brew/dotenvx]
[dotenvx][precommit] ? other install options [https://dotenvx.com/docs/install]
/my/path/to/dotenvx
```
This commit changes the output redirection to use `2>&1`, fixing the issue.
[SC3020]: https://www.shellcheck.net/wiki/SC3020

Fix "command not found" error in precommit script

---

README.md

The part dedicated to .env.ci was referencing the .env.production file.

Fix Readme dedicated to .env.ci

---

src/lib/services/precommit.js

This is a proposal to remove the usage of the `--cached` flag, and include the `HEAD` argument in the `git diff` command
during `dotenvx ext precommit`.
The primary reason for the `precommit` hook is to protect `.env` files from beings accidentally committed in an
unencrypted state and potentially leaking sensitive information such as API keys, passwords, etc. It makes sense to take
the maximum precautions possible to ensure that the `precommit` hook is as effective as possible.
From the `git diff` documentation:
```
git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]
This form is to view the changes you staged for the next commit relative to the named <commit>. Typically you would 
want comparison with the latest commit, so if you do not give <commit>, it defaults to …
```

Remove --cached flag from precommit hook

---

README.md

Correcting the esm export example.
```ts
import '@dotenvx/dotenvx/config'
```
instead of 
```ts
import('@dotenvx/dotenvx/config')
```

Update README.md - correcting esm export example.

---

src/lib/main.d.ts

The type of the result of `set` did not match the actual result.

Fix SetOutput types
